#define BUFFER_SIZE 64
#define RF_FREQUENCY 868E6
#define TX_OUTPUT_POWER 14
#define LORA_BANDWIDTH 125E3
#define LORA_SPREADING_FACTOR 7
#define LORA_CODINGRATE 5
#define LORA_PREAMBLE_LENGTH 8
#define LORA_FIX_LENGTH_PAYLOAD_ON false
#define LORA_CRC_ENABLED true
#define LORA_FHSS_ENABLED false
#define LORA_NB_SYMB_HOP 4
#define LORA_IQ_INVERSION_ON false
#define RX_TIMEOUT_VALUE 2000
#define TX_TIMEOUT_VALUE 2000

#define AIR_QUALITY_SENSOR_PIN_VSENSOR A2
#define AIR_QUALITY_SENSOR_PIN_VHEATER A1

#define STUDENT_ID 01  // Replace with your actual student ID between 01 and 13